### ISSUE TITLE
Sensors don't do anything?

### ISSUE THREAD

**Issue by ScoreUnder** [let-def/lwd#29]
When trying to fix a scrolling-related bug, I found that sensors don't work:
```ocaml
type sensor_state = {x : int; y : int; w : int; h : int; count : int}

let sensor_text () =
  let state_var = Lwd.var {x = 0; y = 0; w = 0; h = 0; count = 0} in
  let widget state =
    Nottui_widgets.printf ~attr:Notty.A.(bg white ++ fg black) "(%d, %d, %d, %d) updated %d times" state.x state.y state.w state.h state.count
    |> Nottui.Ui.permanent_sensor (fun ~x ~y ~w ~h () ->
      Lwd.set state_var {x; y; w; h; count = succ state.count}
    )
  in
  Lwd.map ~f:widget (Lwd.get state_var)

let () =
  let midpane = Nottui_widgets.v_pane (sensor_text ()) (sensor_text ()) in
  let rightpane = Nottui_widgets.h_pane midpane (sensor_text ()) in
  let root = Nottui_widgets.hbox [sensor_text (); rightpane] in
  Nottui.Ui_loop.run root
```

No matter what I resize (splits or terminal) I get something vaguely like this:
```
(0, 0, 0, 0) updated 0 times(0, 0, 0, 0) updated 0 t (0, 0, 0, 0) updated 0 times









                            (0, 0, 0, 0) updated 0 t



```

Using LWD installed from source at commit `3bfeca4d37560f8778610c51d60d2d1aedfa519d`

**Comment by let-def** [comment]
And sorry for the bug, thanks for reporting :).

In the "fix" branch, I started working on an explicit fixed point operator to give more control over that kind of situation... In your case, it should be able to detect that your mutations is not "well-founded" and print an error message and a backtrace rather than entering an infinite loop.
Though I am not yet satisfied with the design and I have no time to work on that these days :/.

**Comment by ScoreUnder** [comment]
Thank you for looking into it! Would you also happen to know why the size sensor happens at a different point in time to the other sensors? I've been struggling to understand that one.

**Comment by let-def** [comment]
I am open to suggestions for alternative designs.
Or just of interesting examples if it happens to be a problem for your use case.
